export const LANGUAGE_NAME_MAP: Record<string, string> = {
  "en-US": "English (US)",
  "en-GB": "English (UK)",
  "es-ES": "Spanish",
  "fr-FR": "French",
  "de-DE": "German",
  "it-IT": "Italian",
  "pt-BR": "Portuguese (BR)",
  "ja-JP": "Japanese",
  "ko-KR": "Korean",
  "zh-CN": "Chinese (Mandarin)",
  "hi-IN": "Hindi",
  "bn-IN": "Bengali",
  "te-IN": "Telugu",
  "mr-IN": "Marathi",
  "ta-IN": "Tamil",
  "ur-IN": "Urdu",
  "gu-IN": "Gujarati",
  "kn-IN": "Kannada",
  "or-IN": "Odia",
  "ml-IN": "Malayalam",
  "pa-IN": "Punjabi",
  "as-IN": "Assamese",
};
